# Generated by Django 5.1.1 on 2024-10-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hub", "0001_initial"),
        ("player", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pageconnectregistration",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="page_connect_registrations",
                to="player.player",
            ),
        ),
    ]
