# Generated by Django 6.1.1 on 2026-09-11 18:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('task', models.CharField(max_length=160)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('queue', models.CharField(default='celery', max_length=40)),
                ('generation', models.PositiveBigIntegerField(default=1)),
                ('completed_generation', models.PositiveBigIntegerField(default=0)),
                ('due_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('published_until', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=160)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['queue', 'due_at'], name='background_queue_due')],
            },
        ),
    ]
