# Generated by Django 6.1.1 on 2026-09-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kwt_common', '0002_recover_pending_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundjob',
            name='next_due_at',
            field=models.DateTimeField(null=True),
        ),
    ]
