services:
  kwt-uwsgi:
    image: butros10/kwt-uwsgi:latest
    container_name: kwt-uwsgi
    ports:
      - "1664:1664"
    env_file:
      - .env
    networks:
      - kwt-net

  kwt-daphne:
    image: butros10/kwt-daphne:latest
    container_name: kwt-daphne
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - kwt-redis
    networks:
      - kwt-net

  kwt-redis:
    image: redis:latest
    container_name: kwt-redis
    networks:
      - kwt-net

  kwt-minio:
    image: minio/minio:latest
    container_name: kwt-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /home/butros/kwt/:/data
    networks:
      - kwt-net

  kwt-collectstatic:
    image: kwt-collectstatic:latest
    container_name: kwt-collectstatic
    depends_on:
      - kwt-minio
    environment:
      - .env
    networks:
      - kwt-net

  kwt-migrate:
    image: kwt-nginx:latest
    container_name: kwt-migrate
    command: python manage.py migrate
    env_file:
      - .env
    networks:
      - kwt-net

networks:
  kwt-net:
    driver: bridge