services:
  kwt-uwsgi:
    build:
      context: .
      dockerfile: ./docker/uwsgi.Dockerfile
    container_name: kwt-uwsgi
    ports:
      - "1664:1664"
    env_file:
      - .env
    networks:
      - kwt-net

  kwt-daphne:
    build:
      context: .
      dockerfile: ./docker/daphne.Dockerfile
    container_name: kwt-daphne
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - kwt-redis
    networks:
      - kwt-net

  kwt-redis:
    image: redis:latest
    container_name: kwt-redis
    networks:
      - kwt-net

  kwt-nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    container_name: kwt-nginx
    ports:
      - "80:80"
    depends_on:
      - kwt-uwsgi
      - kwt-daphne
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - kwt-net

  kwt-minio:
    image: minio/minio:latest
    container_name: kwt-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    networks:
      - kwt-net

  kwt-collectstatic:
    build:
      context: .
      dockerfile: ./docker/collectstatic.Dockerfile
    container_name: kwt-collectstatic
    depends_on:
      - kwt-minio
    environment:
      - .env
    networks:
      - kwt-net

  kwt-migrate:
    build:
      context: .
      dockerfile: ./docker/uwsgi.Dockerfile
    container_name: kwt-migrate
    command: python manage.py migrate
    env_file:
      - .env
    networks:
      - kwt-net
  
  kwt-postgres:
    image: postgres:latest
    container_name: kwt-postgres
    env_file:
      - .env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - kwt-net

networks:
  kwt-net:
    driver: bridge