services:
    kwt-migrate:
        build:
            context: .
            dockerfile: ./docker/uwsgi.Dockerfile
        container_name: kwt-migrate
        command: python manage.py migrate
        env_file:
            - .env
        networks:
            - monorepo_test-net
        volumes:
            - ./apps:/app/apps
            - ./korfbal:/app/korfbal
            - ./manage.py:/app/manage.py

    kwt-collectstatic:
        build:
            context: .
            dockerfile: ./docker/collectstatic.Dockerfile
        container_name: kwt-collectstatic
        env_file:
            - .env
        networks:
            - monorepo_test-net
        volumes:
            - ./apps:/app/apps
            - ./korfbal:/app/korfbal
            - ./static_workfile:/app/static_workfile
            - ./manage.py:/app/manage.py

    kwt-uwsgi:
        build:
            context: .
            dockerfile: ./docker/uwsgi.Dockerfile
        container_name: kwt-uwsgi
        command: python manage.py runserver 0.0.0.0:1664
        env_file:
            - .env
        volumes:
            - ./apps:/app/apps
            - ./korfbal:/app/korfbal
            - ./templates:/app/templates
            - ./manage.py:/app/manage.py
        networks:
            - monorepo_test-net
        depends_on:
            kwt-migrate:
                condition: service_completed_successfully

    kwt-daphne:
        build:
            context: .
            dockerfile: ./docker/daphne.Dockerfile
        container_name: kwt-daphne
        env_file:
            - .env
        volumes:
            - ./apps:/kwt_daphne/apps
            - ./korfbal:/kwt_daphne/korfbal
            - ./manage.py:/kwt_daphne/manage.py
        depends_on:
            kwt-migrate:
                condition: service_completed_successfully
        networks:
            - monorepo_test-net

    kwt-nginx:
        image: nginx:latest
        container_name: kwt-nginx
        volumes:
            - ./docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/conf/nginx/ssl:/etc/nginx/ssl
        depends_on:
            - kwt-uwsgi
            - kwt-daphne
        networks:
            - monorepo_test-net

networks:
    monorepo_test-net:
        external: true