# Generated by Django 5.1.1 on 2024-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="/static/images/player/blank-profile-picture.png",
                upload_to="profile_pictures/",
            ),
        ),
    ]
