# Generated by Django 5.1.5 on 2025-02-04 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0004_alter_player_profile_picture"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="goal_song_uri",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="player",
            name="song_start_time",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SpotifyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_token", models.CharField(max_length=500)),
                ("refresh_token", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("spotify_user_id", models.CharField(max_length=100, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
