# Generated by Django 5.1.5 on 2025-12-16 00:00

import django.db.models.deletion
from bg_uuidv7 import uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0006_alter_player_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerSong",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spotify_url", models.URLField(max_length=500)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("artists", models.CharField(blank=True, max_length=255)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                ("start_time_seconds", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("downloading", "Downloading"),
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="player_songs/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="player.player",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
