# Generated by Django 5.1.5 on 2025-12-17 00:00

from __future__ import annotations

import django.db.models.deletion
from bg_uuidv7 import uuidv7
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0008_player_goal_song_song_ids"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedSong",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("spotify_url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("artists", models.CharField(blank=True, max_length=255)),
                ("duration_seconds", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("downloading", "Downloading"),
                            ("uploading", "Uploading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "audio_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="cached_songs/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="playersong",
            name="cached_song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="player_entries",
                to="player.cachedsong",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersong",
            constraint=models.UniqueConstraint(
                condition=Q(cached_song__isnull=False),
                fields=("player", "cached_song"),
                name="unique_player_cached_song",
            ),
        ),
    ]
