# Generated by Django 5.2.7 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0017_playerpushsubscription_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
