# Generated by Django 6.1 on 2026-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0020_enqueue_goal_song_clip_preparation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='playerclubmembership',
            name='pcm_player_idx',
        ),
        migrations.RemoveIndex(
            model_name='playerclubmembership',
            name='pcm_club_idx',
        ),
    ]
