# Generated by Django 6.1 on 2026-09-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0022_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='knkv_photo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
