# Generated by Django 6.1.1 on 2026-09-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0024_alter_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
