# Generated by Django 6.1.1 on 2026-09-09 09:29

import django.db.models.deletion
from django.db import migrations, models


def copy_selections(apps, schema_editor):
    """Retain valid selections in order; stale references have no song to retain."""
    from uuid import UUID

    alias = schema_editor.connection.alias
    songs = apps.get_model("player", "PlayerSong")
    for app, model, field, selection, owner_field in (
        ("player", "Player", "goal_song_song_ids", "PlayerGoalSongSelection", "player_id"),
        ("team", "TeamData", "fallback_goal_song_song_ids", "TeamGoalSongSelection", "team_data_id"),
    ):
        owners = apps.get_model(app, model)
        selections = apps.get_model("player", selection)
        for owner in owners.objects.using(alias).only("pk", field).iterator(chunk_size=500):
            ids = []
            for value in getattr(owner, field) or []:
                try:
                    song_id = UUID(str(value))
                except (ValueError, TypeError):
                    continue
                if song_id not in ids:
                    ids.append(song_id)
            existing = set(songs.objects.using(alias).filter(pk__in=ids).values_list("pk", flat=True))
            selections.objects.using(alias).bulk_create([
                selections(**{owner_field: owner.pk, "song_id": song_id, "position": position})
                for position, song_id in enumerate(ids) if song_id in existing
            ])


def restore_selections(apps, schema_editor):
    """Restore ordered JSON for a schema rollback before removing references."""
    alias = schema_editor.connection.alias
    for app, model, field, selection, owner_field in (
        ("player", "Player", "goal_song_song_ids", "PlayerGoalSongSelection", "player_id"),
        ("team", "TeamData", "fallback_goal_song_song_ids", "TeamGoalSongSelection", "team_data_id"),
    ):
        owners = apps.get_model(app, model)
        selections = apps.get_model("player", selection)
        for owner in owners.objects.using(alias).only("pk").iterator(chunk_size=500):
            ids = [str(value) for value in selections.objects.using(alias).filter(**{owner_field: owner.pk}).order_by("position").values_list("song_id", flat=True)]
            owners.objects.using(alias).filter(pk=owner.pk).update(**{field: ids})


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_player_archived_at'),
        ('team', '0010_teamrostermembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerGoalSongSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_song_selections', to='player.player')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playersong')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('player', 'position'), name='unique_player_song_position'), models.UniqueConstraint(fields=('player', 'song'), name='unique_player_song_selection')],
            },
        ),
        migrations.CreateModel(
            name='TeamGoalSongSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playersong')),
                ('team_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_song_selections', to='team.teamdata')),
            ],
            options={
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('team_data', 'position'), name='unique_team_song_position'), models.UniqueConstraint(fields=('team_data', 'song'), name='unique_team_song_selection')],
            },
        ),
        migrations.RunPython(copy_selections, restore_selections),
    ]
