# Generated by Django 6.1.1 on 2026-09-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0026_playergoalsongselection_teamgoalsongselection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='goal_song_song_ids',
        ),
    ]
