# Generated by Django 6.1.1 on 2026-09-09 13:18

import apps.player.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0027_remove_player_goal_song_song_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.player.media_paths.player_picture_path),
        ),
        migrations.AlterField(
            model_name='playersong',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.player.media_paths.player_song_path),
        ),
    ]
