# Generated by Django 6.1.1 on 2026-09-14 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0028_alter_player_profile_picture_and_more'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersong',
            name='team_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='team.teamdata'),
        ),
        migrations.AlterField(
            model_name='playersong',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='player.player'),
        ),
        migrations.AddConstraint(
            model_name='playersong',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('player__isnull', False), ('team_data__isnull', True)), models.Q(('player__isnull', True), ('team_data__isnull', False)), _connector='OR'), name='song_has_one_owner'),
        ),
        migrations.AddConstraint(
            model_name='playersong',
            constraint=models.UniqueConstraint(condition=models.Q(('cached_song__isnull', False)), fields=('team_data', 'cached_song'), name='unique_team_cached_song'),
        ),
    ]
