# Generated by Django 6.1.1 on 2026-09-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0029_team_song_ownership'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playersong',
            name='unique_player_cached_song',
        ),
        migrations.RemoveConstraint(
            model_name='playersong',
            name='unique_team_cached_song',
        ),
        migrations.AddField(
            model_name='playersong',
            name='clip_duration_seconds',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='playersong',
            name='clip_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddConstraint(
            model_name='playersong',
            constraint=models.CheckConstraint(condition=models.Q(('clip_duration_seconds__gte', 1), ('clip_duration_seconds__lte', 15)), name='song_clip_duration_bounds'),
        ),
    ]
