# Generated by Django 6.1.1 on 2026-09-14 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0030_multiple_song_clips'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='playersong',
            name='library_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_copies', to='player.playersong'),
        ),
        migrations.AddConstraint(
            model_name='playersong',
            constraint=models.UniqueConstraint(fields=('team_data', 'library_source'), name='unique_team_library_clip'),
        ),
    ]
