# Generated by Django 6.1.1 on 2026-09-29 15:47

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0031_playersong_library_source_and_more'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchLiveActivity',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('push_token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(default='ios', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('last_pushed_revision', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activities', to='schedule.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'is_active'], name='live_activity_match_active_idx')],
            },
        ),
    ]
