# Generated by Django 5.2.14 on 2026-09-07 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0005_matchmvpvote_anonymous_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SyncLease',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('owner', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('class_name', models.CharField(blank=True, max_length=255)),
                ('sport', models.CharField(blank=True, db_index=True, max_length=80)),
                ('standings_synced_at', models.DateTimeField(null=True)),
                ('results_filtered', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(db_index=True, max_length=40)),
                ('home_score', models.PositiveIntegerField(null=True)),
                ('away_score', models.PositiveIntegerField(null=True)),
                ('automatic_result', models.BooleanField(default=False)),
                ('result_observed_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
                ('pool', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='competition.pool')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResultRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_at', models.DateTimeField()),
                ('status', models.CharField(max_length=40)),
                ('home_score', models.PositiveIntegerField(null=True)),
                ('away_score', models.PositiveIntegerField(null=True)),
                ('automatic_result', models.BooleanField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='competition.match')),
            ],
        ),
        migrations.CreateModel(
            name='SyncResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32)),
                ('source_id', models.CharField(blank=True, default='', max_length=80)),
                ('next_sync_at', models.DateTimeField(db_index=True)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('etag', models.CharField(blank=True, max_length=512)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=80)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.season')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('sport', models.CharField(db_index=True, max_length=80)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.club')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PoolEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing', models.JSONField(default=dict)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='competition.pool')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_matches', to='competition.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_matches', to='competition.team'),
        ),
        migrations.AddConstraint(
            model_name='pool',
            constraint=models.UniqueConstraint(fields=('season', 'external_id'), name='pool_season_source'),
        ),
        migrations.AddConstraint(
            model_name='syncresource',
            constraint=models.UniqueConstraint(fields=('season', 'kind', 'source_id'), name='competition_resource_once'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('season', 'external_id'), name='team_season_source'),
        ),
        migrations.AddConstraint(
            model_name='poolentry',
            constraint=models.UniqueConstraint(fields=('pool', 'team'), name='pool_team_once'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'status', 'starts_at'], name='competition_season__640f6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('season', 'external_id'), name='match_season_source'),
        ),
    ]
