# Generated by Django 6.1 on 2026-09-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_clubadmin_unique_together_and_more'),
        ('competition', '0002_trafficstate_match_results_checked_at_teamgroup_and_more'),
        ('schedule', '0008_remove_match_schedule_ma_home_te_5e2ac9_idx_and_more'),
        ('team', '0006_remove_teamdata_team_teamda_team_id_18931e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='local_club',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_identity', to='club.club'),
        ),
        migrations.AddField(
            model_name='match',
            name='local_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_identity', to='schedule.match'),
        ),
        migrations.AddField(
            model_name='pool',
            name='local_pool',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_identity', to='schedule.seasonpool'),
        ),
        migrations.AddField(
            model_name='teamgroup',
            name='local_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_groups', to='team.team'),
        ),
        migrations.AddConstraint(
            model_name='teamgroup',
            constraint=models.UniqueConstraint(fields=('season', 'local_team'), name='competition_local_team_once'),
        ),
    ]
