# Generated by Django 6.1 on 2026-09-07 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0003_club_local_club_match_local_match_pool_local_pool_and_more'),
        ('team', '0007_team_unique_team_name_per_club_and_more'),
        ('game_tracker', '0036_matchdata_score_source'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='published_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='local_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamgroup',
            name='local_team_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_identity', to='team.teamdata'),
        ),
    ]
