# Generated by Django 6.1 on 2026-09-07 20:12

from django.db import migrations, models
from django.utils import timezone


def rediscover_logos(apps, schema_editor):
    """Refresh only club lists to discover logo references for existing imports."""
    apps.get_model("competition", "SyncResource").objects.using(schema_editor.connection.alias).filter(kind="clubs").update(fetched_at=None, etag="", next_sync_at=timezone.now())



class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0004_match_local_created_match_published_at_and_more'),
    ]

    operations = [
        migrations.RunPython(rediscover_logos, migrations.RunPython.noop),
        migrations.AddField(
            model_name='club',
            name='cached_logo',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='club',
            name='logo_bucket',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='club',
            name='logo_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='club',
            name='published_logo',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
