# Generated by Django 6.1 on 2026-09-07 22:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_club_cached_logo_club_logo_bucket_club_logo_hash_and_more'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficstate',
            name='rate_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HistoricalResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=20)),
                ('source_id', models.CharField(max_length=80)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sport', models.CharField(blank=True, max_length=80)),
                ('state', models.CharField(db_index=True, default='pending', max_length=20)),
                ('coverage', models.CharField(default='unknown', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('evidence', models.JSONField(default=dict)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fetched_at', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('etag', models.CharField(blank=True, max_length=512)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDiscovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=512)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='competition.historicalresource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discoveries', to='competition.historicalresource')),
            ],
        ),
        migrations.AddIndex(
            model_name='historicalresource',
            index=models.Index(fields=['state', 'next_attempt_at'], name='competition_state_7acff9_idx'),
        ),
        migrations.AddConstraint(
            model_name='historicalresource',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='history_valid_date_interval'),
        ),
        migrations.AddConstraint(
            model_name='historicaldiscovery',
            constraint=models.UniqueConstraint(fields=('resource', 'reference'), name='history_discovery_once'),
        ),
    ]
