# Generated by Django 6.1 on 2026-09-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_trafficstate_rate_limited_historicalresource_and_more'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=20)),
                ('age_group', models.CharField(max_length=20)),
                ('team_kind', models.CharField(max_length=20)),
                ('colour', models.CharField(max_length=20)),
                ('playing_format', models.CharField(max_length=20)),
                ('level', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='mapping_evidence',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pool',
            name='mapping_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='pool',
            name='mapping_override',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pool',
            name='mapping_status',
            field=models.CharField(default='unresolved', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='mapping_version',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='pool',
            name='competition_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pools', to='competition.competitionclass'),
        ),
        migrations.CreateModel(
            name='CompetitionEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=20)),
                ('phase', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
        ),
        migrations.AddField(
            model_name='competitionclass',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.competitionedition'),
        ),
        migrations.AddConstraint(
            model_name='competitionedition',
            constraint=models.UniqueConstraint(fields=('season', 'discipline', 'phase', 'gender'), name='competition_edition_context_once'),
        ),
        migrations.AddConstraint(
            model_name='competitionclass',
            constraint=models.UniqueConstraint(fields=('edition', 'code', 'category', 'age_group', 'team_kind', 'colour', 'playing_format'), name='competition_class_context_once'),
        ),
    ]
