# Generated by Django 6.1 on 2026-09-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_trafficstate_rate_limited_historicalresource_and_more'),
        ('player', '0022_alter_player_options_alter_player_managers_and_more'),
        ('team', '0007_team_unique_team_name_per_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(null=True)),
                ('shirt_number', models.CharField(blank=True, max_length=10)),
                ('local_link_created', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knkv_memberships', to='player.player')),
                ('published_team_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.teamdata')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_memberships', to='competition.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('player', 'team'), name='competition_active_roster_once')],
            },
        ),
    ]
