# Generated by Django 6.1 on 2026-09-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0007_competition_classification'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('label', models.CharField(max_length=255)),
                ('published_on', models.DateField()),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('column', models.PositiveSmallIntegerField()),
                ('section', models.CharField(max_length=255)),
                ('pool_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('match_day', models.CharField(max_length=20)),
                ('average_age', models.DecimalField(decimal_places=1, max_digits=4, null=True)),
                ('knkv_points', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('classification', models.JSONField(default=dict)),
                ('link_status', models.CharField(default='unmatched', max_length=30)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='competition.poolentry')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition.allocationsource')),
            ],
        ),
        migrations.AddConstraint(
            model_name='allocationsource',
            constraint=models.UniqueConstraint(fields=('season', 'digest'), name='competition_allocation_source_once'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(fields=('source', 'row_number', 'column'), name='competition_allocation_row_once'),
        ),
    ]
