# Generated by Django 6.1 on 2026-09-08 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_allocation_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='competition_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='competition.competitionclass'),
        ),
    ]
