# Generated by Django 6.1.1 on 2026-09-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_merge_rosters_and_allocations'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
        ('team', '0007_team_unique_team_name_per_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rostermembership',
            name='local_coach_link_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rostermembership',
            name='local_staff_link_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rostermembership',
            name='roles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='team',
            name='local_team_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='competition_variants', to='team.teamdata'),
        ),
        migrations.CreateModel(
            name='SeasonBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=80)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_season_bindings', to='schedule.season')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'sport'), name='competition_scope_sport_once')],
            },
        ),
    ]
