# Generated by Django 6.1.1 on 2026-09-08 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0010_merge_rosters_and_allocations'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_ids', models.JSONField(default=list)),
                ('effective_at', models.DateTimeField()),
                ('b_scale', models.FloatField()),
                ('b_k_factor', models.FloatField()),
                ('active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='schedule.season')),
            ],
        ),
    ]
