# Generated by Django 6.1.1 on 2026-09-08 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_rostermembership_local_coach_link_created_and_more'),
        ('player', '0023_player_knkv_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('selected', 'Selected, starting role unknown'), ('starter', 'Starter'), ('substitute', 'Substitute'), ('staff', 'Staff')], max_length=16)),
                ('roles', models.JSONField(default=list)),
                ('observed_at', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='competition.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'player'), name='competition_match_person_once')],
            },
        ),
    ]
