# Generated by Django 6.1.1 on 2026-09-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_matchmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lineup_observed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
