# Generated by Django 6.1.1 on 2026-09-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0013_match_lineup_observed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='private_lineup_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='private_roster_counts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='team',
            name='roster_observed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
