# Generated by Django 6.1.1 on 2026-09-08 16:01

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor

BATCH_SIZE = 1000


def seed_published_schedule(
    apps: Apps, schema_editor: BaseDatabaseSchemaEditor
) -> None:
    """Seed only fully published snapshots; pending updates retain a quiet baseline."""
    match = apps.get_model("competition", "Match")
    rows = match.objects.using(schema_editor.connection.alias).filter(
        published_at__gte=models.F("updated_at"), local_match__isnull=False
    )
    batch = []
    for row in rows.iterator(chunk_size=BATCH_SIZE):
        row.published_schedule = {
            "starts_at": row.starts_at.isoformat(),
            "status": row.status,
        }
        batch.append(row)
        if len(batch) == BATCH_SIZE:
            match.objects.using(schema_editor.connection.alias).bulk_update(
                batch, ["published_schedule"], batch_size=BATCH_SIZE
            )
            batch.clear()
    if batch:
        match.objects.using(schema_editor.connection.alias).bulk_update(
            batch, ["published_schedule"], batch_size=BATCH_SIZE
        )


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0015_merge_rating_configuration_and_roster_counts"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="published_schedule",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(seed_published_schedule, migrations.RunPython.noop),
    ]
