# Generated by Django 6.1.1 on 2026-09-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_match_published_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='schedule_notification_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
