# Generated by Django 6.1.1 on 2026-09-09 13:30

from django.db import migrations, models


def reset_collection_etags(apps, schema_editor):
    """Existing validators have no known membership; refill it on the next poll."""
    apps.get_model("competition", "SyncResource").objects.using(schema_editor.connection.alias).filter(
        kind__in=("club_program", "club_results", "pool_results")
    ).update(etag="")


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0017_schedule_notification_id'),
    ]

    operations = [
        migrations.AddField(model_name='match', name='facility_details', field=models.JSONField(default=dict)),
        migrations.AddField(model_name='match', name='facility_observed_at', field=models.DateTimeField(null=True)),
        migrations.AddField(model_name='match', name='match_rules', field=models.JSONField(default=dict)),
        migrations.AddField(model_name='match', name='rules_observed_at', field=models.DateTimeField(null=True)),
        migrations.AddField(
            model_name='match',
            name='match_periods',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='playing_time_observed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='playing_time_minutes',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='reporting_delay_seconds',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='schedule_checked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='syncresource',
            name='match_ids',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(reset_collection_etags, migrations.RunPython.noop),
    ]
