# Generated by Django 6.1.1 on 2026-09-09 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_match_polling_coverage'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        ('tournament', '0009_tournament_cup_rules_tournamentmatch_cup_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CupCompetition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sport', models.CharField(blank=True, max_length=80)),
                ('local_tournament', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cup', to='tournament.tournament')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.season')),
            ],
        ),
        migrations.CreateModel(
            name='CupFixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(blank=True, max_length=120)),
                ('round_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner_to_side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=4)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='competition.cupcompetition')),
                ('local_match', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_cup_fixture', to='tournament.tournamentmatch')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cup_fixture', to='competition.match')),
                ('next_fixture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competition.cupfixture')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cupcompetition',
            constraint=models.UniqueConstraint(fields=('season', 'name', 'sport'), name='unique_source_cup'),
        ),
    ]
