# Generated by Django 6.1.1 on 2026-09-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_match_polling_coverage'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('status', models.CharField(default='running', max_length=32)),
                ('summary', models.JSONField(default=dict)),
                ('backlog', models.JSONField(default=dict)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.season')),
            ],
            options={
                'indexes': [models.Index(fields=['season', 'started_at'], name='competition_season__9ca005_idx')],
            },
        ),
    ]
