# Generated by Django 6.1.1 on 2026-09-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_merge_cup_and_sync_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='missing_result_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='results_attempted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='diagnostics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='heartbeat_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='syncrun',
            name='lease_owner',
            field=models.UUIDField(null=True),
        ),
    ]
