# Generated by Django 6.1.1 on 2026-09-11 09:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0021_import_recovery'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('auto_substitutions', models.BooleanField(default=False)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchFormSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('import', 'import'), ('publish', 'publish'), ('substitutions', 'substitutions')], max_length=20)),
                ('state', models.CharField(default='pending', max_length=20)),
                ('expected_revision', models.PositiveBigIntegerField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('player_count', models.PositiveSmallIntegerField(default=0)),
                ('event_count', models.PositiveSmallIntegerField(default=0)),
                ('published_event_ids', models.JSONField(default=list)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competition.matchformaccess')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.match')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('access', 'match', 'action'), name='competition_match_form_action_once')],
            },
        ),
    ]
