# Generated by Django 6.1.1 on 2026-09-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0022_matchformaccess_matchformsync'),
        ('player', '0028_alter_player_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchformsync',
            name='captain_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='player.player'),
        ),
    ]
