# Generated by Django 6.1.1 on 2026-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0023_matchformsync_captain_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchformsync',
            name='publication_intent',
            field=models.JSONField(default=dict),
        ),
    ]
