# Generated by Django 6.1.1 on 2026-09-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0024_matchformsync_publication_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchformsync',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
    ]
