# Generated by Django 6.1.1 on 2026-09-20 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competition", "0025_matchformsync_automatic"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreForecastReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artifact_sha256", models.CharField(max_length=64, unique=True)),
                ("incumbent_sha256", models.CharField(max_length=64)),
                ("source_reference", models.CharField(max_length=255)),
                ("training_cutoff", models.DateTimeField()),
                ("available_from", models.DateTimeField()),
                ("training_matches", models.PositiveIntegerField()),
                ("contexts", models.PositiveIntegerField()),
                ("automated_passed", models.BooleanField(default=False)),
                ("candidate_metrics", models.JSONField(default=dict)),
                ("incumbent_metrics", models.JSONField(default=dict)),
                ("head_to_head", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collecting", "Keep collecting evidence"),
                            ("rejected", "Rejected"),
                            (
                                "approved_pending_activation",
                                "Approved, pending activation",
                            ),
                            ("activated", "Activated"),
                        ],
                        default="collecting",
                        max_length=32,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                ("decision_history", models.JSONField(default=list)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_forecast_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-available_from",),
                "permissions": [
                    (
                        "decide_scoreforecastreview",
                        "Can decide score forecast reviews",
                    )
                ],
            },
        ),
    ]
