# Generated by Django 6.1.1 on 2026-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0026_scoreforecastreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='dissolved',
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
