# Generated by Django 6.1.1 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0027_club_dissolved'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='historicalresource',
            index=models.Index(fields=['kind', 'state', 'next_attempt_at'], name='history_kind_ready'),
        ),
    ]
