# Generated by Django 6.1.1 on 2026-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0028_history_kind_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='colors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
