# Generated by Django 6.1.1 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0029_club_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='contact',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='club',
            name='sports',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
