# Generated by Django 6.1.1 on 2026-10-02 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0030_club_contact_sports'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRating',
            fields=[
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='elo_rating', serialize=False, to='competition.match')),
                ('home_rating', models.FloatField()),
                ('away_rating', models.FloatField()),
                ('home_expected', models.FloatField()),
                ('home_change', models.FloatField()),
                ('home_games', models.PositiveIntegerField()),
                ('away_games', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamRating',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='competition_rating', serialize=False, to='team.team')),
                ('rating', models.FloatField(db_index=True)),
                ('phase_start', models.FloatField()),
                ('games', models.PositiveIntegerField()),
                ('last_played_at', models.DateTimeField()),
                ('comparison_group', models.CharField(max_length=36)),
                ('model', models.CharField(max_length=20)),
                ('competition_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competition.competitionclass')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schedule.season')),
            ],
        ),
    ]
