# Generated by Django 6.1.1 on 2026-10-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0031_team_elo'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchrating',
            name='away_phase_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchrating',
            name='away_team',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.team'),
        ),
        migrations.AddField(
            model_name='matchrating',
            name='home_phase_start',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='matchrating',
            name='home_team',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='team.team'),
        ),
        migrations.AddField(
            model_name='matchrating',
            name='phase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schedule.season'),
        ),
        migrations.AddField(
            model_name='matchrating',
            name='starts_at',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['updated_at'], name='competition_match_updated'),
        ),
        migrations.AddIndex(
            model_name='matchrating',
            index=models.Index(fields=['home_team', 'starts_at'], name='rating_home_start'),
        ),
        migrations.AddIndex(
            model_name='matchrating',
            index=models.Index(fields=['away_team', 'starts_at'], name='rating_away_start'),
        ),
    ]
