# Generated by Django 6.1.1 on 2026-10-02 10:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0032_incremental_team_elo'),
        ('schedule', '0012_season_competition_context'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='seasonbinding',
            name='competition_scope_sport_once',
        ),
        migrations.AddField(
            model_name='pool',
            name='competition_part',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='phase',
            field=models.CharField(blank=True, db_default='', default='', max_length=12),
        ),
        migrations.AddField(
            model_name='pool',
            name='phase_evidence',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='seasonbinding',
            name='phase',
            field=models.CharField(blank=True, db_default='', default='', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='seasonbinding',
            constraint=models.UniqueConstraint(fields=('scope', 'sport', 'phase'), name='competition_scope_sport_phase_once'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='competition.team'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='team_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_participations', to='team.teamdata'),
        ),
        migrations.AddConstraint(
            model_name='teamparticipation',
            constraint=models.UniqueConstraint(fields=('team', 'phase'), name='competition_team_phase_once'),
        ),
    ]
