# Generated by Django 6.1.1 on 2026-10-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0032_incremental_team_elo'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='cohort',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='historicalresource',
            index=models.Index(fields=['cohort', 'state'], name='history_cohort_state'),
        ),
    ]
