# Generated by Django 6.1.1 on 2026-10-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0034_merge_competition_periods_history_lineup_cohort'),
        ('schedule', '0014_season_data_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='current_directory_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='metadata_observations',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='club',
            name='sport_definitions',
            field=models.JSONField(blank=True, db_default=models.Value([], output_field=models.JSONField()), default=list),
        ),
        migrations.AddField(
            model_name='match',
            name='metadata_observations',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='match',
            name='source_context',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='pool',
            name='source_context',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='pool',
            name='standings_provenance',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='poolentry',
            name='computed_standing',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='source_context',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddIndex(
            model_name='pool',
            index=models.Index(condition=models.Q(('phase', ''), ('phase_evidence', {})), fields=['id'], name='competition_period_backlog'),
        ),
        migrations.AddIndex(
            model_name='syncresource',
            index=models.Index(fields=['kind', 'source_id'], name='competition_resource_identity'),
        ),
    ]
