"""URL routes for player API."""

from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .views import (
    CurrentPlayerAPIView,
    CurrentPlayerFollowedTeamsAPIView,
    CurrentPlayerGoalSongAPIView,
    CurrentPlayerPrivacySettingsAPIView,
    CurrentPlayerPushSubscriptionsAPIView,
    CurrentPlayerSongDetailAPIView,
    CurrentPlayerSongRetryAPIView,
    CurrentPlayerSongsAPIView,
    CurrentPlayerTeamsAPIView,
    CurrentPlayerTestPushNotificationAPIView,
    PlayerConnectedClubRecentResultsAPIView,
    PlayerFollowedTeamsAPIView,
    PlayerOverviewAPIView,
    PlayerSongClipAPIView,
    PlayerStatsAPIView,
    PlayerTeamsAPIView,
    PlayerViewSet,
    SpotifyCallbackView,
    SpotifyConnectAPIView,
    SpotifyPauseAPIView,
    SpotifyPlayAPIView,
    UploadGoalSongAPIView,
    UploadProfilePictureAPIView,
)


router = DefaultRouter()
router.register(r"players", PlayerViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("me/", CurrentPlayerAPIView.as_view(), name="player-current"),
    path(
        "me/followed-teams/",
        CurrentPlayerFollowedTeamsAPIView.as_view(),
        name="player-followed-teams-current",
    ),
    path(
        "me/teams/",
        CurrentPlayerTeamsAPIView.as_view(),
        name="player-teams-current",
    ),
    path(
        "me/privacy-settings/",
        CurrentPlayerPrivacySettingsAPIView.as_view(),
        name="player-privacy-settings",
    ),
    path(
        "me/push-subscriptions/",
        CurrentPlayerPushSubscriptionsAPIView.as_view(),
        name="player-push-subscriptions",
    ),
    path(
        "me/push-subscriptions/test/",
        CurrentPlayerTestPushNotificationAPIView.as_view(),
        name="player-push-subscriptions-test",
    ),
    path(
        "me/goal-song/",
        CurrentPlayerGoalSongAPIView.as_view(),
        name="player-goal-song",
    ),
    path(
        "me/songs/",
        CurrentPlayerSongsAPIView.as_view(),
        name="player-songs",
    ),
    path(
        "me/songs/<uuid:song_id>/",
        CurrentPlayerSongDetailAPIView.as_view(),
        name="player-song-detail",
    ),
    path(
        "me/songs/<uuid:song_id>/retry/",
        CurrentPlayerSongRetryAPIView.as_view(),
        name="player-song-retry",
    ),
    path(
        "api/upload_profile_picture/",
        UploadProfilePictureAPIView.as_view(),
        name="player-upload-profile-picture",
    ),
    path(
        "api/upload_goal_song/",
        UploadGoalSongAPIView.as_view(),
        name="player-upload-goal-song",
    ),
    path(
        "api/songs/<uuid:song_id>/clip/",
        PlayerSongClipAPIView.as_view(),
        name="player-song-clip",
    ),
    path(
        "spotify/connect/",
        SpotifyConnectAPIView.as_view(),
        name="player-spotify-connect",
    ),
    path(
        "spotify/callback/",
        SpotifyCallbackView.as_view(),
        name="player-spotify-callback",
    ),
    path(
        "spotify/play/",
        SpotifyPlayAPIView.as_view(),
        name="player-spotify-play",
    ),
    path(
        "spotify/pause/",
        SpotifyPauseAPIView.as_view(),
        name="player-spotify-pause",
    ),
    path(
        "me/connected-clubs/recent-results/",
        PlayerConnectedClubRecentResultsAPIView.as_view(),
        name="player-connected-clubs-recent-results",
    ),
    path(
        "me/overview/",
        PlayerOverviewAPIView.as_view(),
        name="player-overview",
    ),
    path(
        "players/<uuid:player_id>/overview/",
        PlayerOverviewAPIView.as_view(),
        name="player-overview-detail",
    ),
    path(
        "players/<uuid:player_id>/followed-teams/",
        PlayerFollowedTeamsAPIView.as_view(),
        name="player-followed-teams-detail",
    ),
    path(
        "players/<uuid:player_id>/teams/",
        PlayerTeamsAPIView.as_view(),
        name="player-teams-detail",
    ),
    path(
        "me/stats/",
        PlayerStatsAPIView.as_view(),
        name="player-stats-current",
    ),
    path(
        "players/<uuid:player_id>/stats/",
        PlayerStatsAPIView.as_view(),
        name="player-stats",
    ),
]
