# Generated by Django 5.2.15 on 2026-08-22 09:18

import apps.tournament.models
import bg_uuidv7.bg_uuidv7
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0004_alter_club_logo'),
        ('team', '0005_teamdata_fallback_goal_song_song_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('timezone', models.CharField(default='Europe/Amsterdam', max_length=64)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('live', 'Live'), ('finished', 'Finished'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted')], default='public', max_length=16)),
                ('display_token', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, unique=True)),
                ('win_points', models.SmallIntegerField(default=2)),
                ('draw_points', models.SmallIntegerField(default=1)),
                ('loss_points', models.SmallIntegerField(default=0)),
                ('tiebreakers', models.JSONField(default=apps.tournament.models.default_tiebreakers)),
                ('match_duration_minutes', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(240)])),
                ('changeover_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(120)])),
                ('minimum_rest_minutes', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(240)])),
                ('live_revision', models.PositiveBigIntegerField(default=0)),
                ('live_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='club.club')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_korfbal_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentDisplayConfig',
            fields=[
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='display_config', serialize=False, to='tournament.tournament')),
                ('rotation_seconds', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)])),
                ('show_live', models.BooleanField(default=True)),
                ('show_standings', models.BooleanField(default=True)),
                ('show_upcoming', models.BooleanField(default=True)),
                ('show_recent', models.BooleanField(default=True)),
                ('accent_color', models.CharField(default='#d6ff00', max_length=16)),
                ('announcement', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentField',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='tournament.tournament')),
            ],
            options={
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('scorekeeper', 'Scorekeeper')], max_length=16)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorekeepers', to='tournament.tournamentfield')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_roles', to='tournament.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='korfbal_tournament_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tournament',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='managed_korfbal_tournaments', through='tournament.TournamentMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentPool',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournament.tournament')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('match_number', models.PositiveIntegerField(default=1)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('final', 'Final'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16)),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('winner_to_side', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], max_length=8)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.tournamentfield')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_matches', to='tournament.tournamentmatch')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournament')),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.tournamentpool')),
            ],
            options={
                'ordering': ['starts_at', 'match_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentPoolEntry',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('seed_order', models.PositiveSmallIntegerField(default=1)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='tournament.tournamentpool')),
            ],
            options={
                'ordering': ['seed_order', 'team__name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResultAudit',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('previous_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_home_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('new_away_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('previous_status', models.CharField(max_length=16)),
                ('new_status', models.CharField(max_length=16)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_result_changes', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_audits', to='tournament.tournamentmatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentStage',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('pool', 'Pool'), ('knockout', 'Knockout'), ('placement', 'Placement'), ('final', 'Final')], max_length=16)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('qualifiers_per_pool', models.PositiveSmallIntegerField(default=0)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournament')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournament.tournamentstage'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.tournamentstage'),
        ),
        migrations.CreateModel(
            name='TournamentStandingAdjustment',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('points', models.SmallIntegerField()),
                ('reason', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournament_standing_adjustments', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='tournament.tournamentpoolentry')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentTeam',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('short_name', models.CharField(blank=True, max_length=32)),
                ('affiliation', models.CharField(blank=True, max_length=120)),
                ('seed', models.PositiveSmallIntegerField(default=1)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=16)),
                ('checked_in', models.BooleanField(default=False)),
                ('withdrawn', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to='team.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournament.tournament')),
            ],
            options={
                'ordering': ['sort_order', 'seed', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentpoolentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_entries', to='tournament.tournamentteam'),
        ),
        migrations.AddField(
            model_name='tournamentpool',
            name='teams',
            field=models.ManyToManyField(related_name='pools', through='tournament.TournamentPoolEntry', to='tournament.tournamentteam'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_tournament_matches', to='tournament.tournamentteam'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_tournament_matches', to='tournament.tournamentteam'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournament_matches', to='tournament.tournamentteam'),
        ),
        migrations.AddConstraint(
            model_name='tournamentfield',
            constraint=models.UniqueConstraint(fields=('tournament', 'label'), name='uniq_tournament_field_label'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmember',
            constraint=models.UniqueConstraint(fields=('tournament', 'user'), name='uniq_tournament_member_user'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['status', 'starts_at'], name='tournament__status_e6ccb5_idx'),
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['owner', 'starts_at'], name='tournament__owner_i_67cfa1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentstage',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_stage_name'),
        ),
        migrations.AddConstraint(
            model_name='tournamentteam',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_team_name'),
        ),
        migrations.AddConstraint(
            model_name='tournamentpoolentry',
            constraint=models.UniqueConstraint(fields=('pool', 'team'), name='uniq_tournament_pool_team'),
        ),
        migrations.AddConstraint(
            model_name='tournamentpool',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_pool_name'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['tournament', 'starts_at'], name='tournament__tournam_ccd4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['tournament', 'status'], name='tournament__tournam_c5c8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['field', 'starts_at'], name='tournament__field_i_8ce052_idx'),
        ),
        migrations.AddIndex(
            model_name='tournamentmatch',
            index=models.Index(fields=['pool', 'status'], name='tournament__pool_id_6f308c_idx'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.CheckConstraint(condition=models.Q(('home_team__isnull', True), ('away_team__isnull', True), models.Q(('home_team', models.F('away_team')), _negated=True), _connector='OR'), name='tournament_match_distinct_teams'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatch',
            constraint=models.UniqueConstraint(fields=('tournament', 'match_number'), name='uniq_tournament_match_number'),
        ),
    ]
