# Generated by Django 6.1 on 2026-09-02 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournamentmatch_field_readiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentpool',
            name='assigned_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pools', to='tournament.tournamentfield'),
        ),
    ]
