# Generated by Django 6.1 on 2026-09-03 08:09

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_tournamentpool_assigned_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmatch',
            name='away_qualifier',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='home_qualifier',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='TournamentFinalGroup',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('format', models.CharField(choices=[('three_pool_wildcard', 'Three pool winners + wildcard'), ('two_pool_cross', 'Two pool crossover')], max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_groups', to='tournament.tournament')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tournamentstage',
            name='final_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='tournament.tournamentfinalgroup'),
        ),
        migrations.AddConstraint(
            model_name='tournamentfinalgroup',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='uniq_tournament_final_group_name'),
        ),
    ]
