# Generated by Django 6.1 on 2026-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_tournamentmatch_referee_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentdisplayconfig',
            name='sponsors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
