# Generated by Django 6.1 on 2026-09-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0007_tournamentdisplayconfig_sponsors"),
    ]

    operations = [
        migrations.AddField(
            model_name="tournamentdisplayconfig",
            name="show_sponsors",
            field=models.BooleanField(default=True),
        ),
    ]
