# Generated by Django 6.1.1 on 2026-09-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_tournamentdisplayconfig_show_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='cup_rules',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='cup_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournamentresultaudit',
            name='new_cup_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tournamentresultaudit',
            name='previous_cup_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='tournamentmatch',
            name='round_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
