# Generated by Django 6.1.1 on 2026-09-26 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_tournament_cup_rules_tournamentmatch_cup_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmember',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scorekeepers', to='tournament.tournamentfield'),
        ),
    ]
