# Generated by Django 6.1.1 on 2026-09-16 06:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('position', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.match')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('proposal', models.JSONField(null=True)),
                ('correction', models.JSONField(null=True)),
                ('history', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('complete', models.BooleanField(default=False)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='video_analysis.recording')),
            ],
            options={
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video_analysis.frame')),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('revision', models.PositiveBigIntegerField(default=0)),
                ('source_digest', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='recording',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='video_analysis.workspace'),
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=24)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_analysis.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='frame',
            constraint=models.UniqueConstraint(fields=('recording', 'source_id'), name='video_frame_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='recording',
            constraint=models.UniqueConstraint(fields=('workspace', 'source_id'), name='video_recording_source_unique'),
        ),
    ]
