# Generated by Django 6.1.1 on 2026-09-16 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_path', models.CharField(max_length=1000)),
                ('bucket', models.CharField(max_length=63)),
                ('object_key', models.CharField(max_length=1000)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('source_mtime_ns', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video_analysis.workspace')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workspace', 'relative_path'), name='video_stored_path_unique')],
            },
        ),
    ]
