# Generated by Django 6.1.1 on 2026-09-24 21:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0002_storedfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPipeline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe', models.JSONField(default=dict)),
                ('progress', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=24)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_analysis.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='ClipReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('history', models.JSONField(default=list)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='video_analysis.analysisjob')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='video_analysis.reviewpipeline')),
            ],
        ),
    ]
