# Generated by Django 6.1.1 on 2026-09-25 05:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0003_reviewpipeline_clipreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('size', models.PositiveBigIntegerField()),
                ('received', models.PositiveBigIntegerField(default=0)),
                ('parts', models.JSONField(default=list)),
                ('status', models.CharField(default='receiving', max_length=24)),
                ('expires_at', models.DateTimeField()),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video_analysis.workspace')),
            ],
        ),
    ]
