# Generated by Django 6.1.1 on 2026-09-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0005_matchvideopublication'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchvideopublication',
            name='breaks',
            field=models.JSONField(default=list),
        ),
    ]
