# Generated by Django 6.1.1 on 2026-09-30 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0006_matchvideopublication_breaks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchVideoAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=8)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField(blank=True)),
                ('start_seconds', models.FloatField()),
                ('end_seconds', models.FloatField(blank=True, null=True)),
                ('player_ids', models.JSONField(blank=True, default=list)),
                ('drawing', models.JSONField(blank=True, null=True)),
                ('visibility', models.CharField(default='viewers', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='video_analysis.recording')),
            ],
            options={
                'ordering': ('start_seconds', 'created_at'),
            },
        ),
    ]
