# Generated by Django 6.1.1 on 2026-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0008_matchvideoplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchvideopublication',
            name='whistles',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='matchvideopublication',
            name='whistles_status',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
