# Generated by Django 6.1.1 on 2026-10-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analysis', '0009_matchvideopublication_whistles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipIdentityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(blank=True, db_default='', default='', max_length=16)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='preparing', max_length=16)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('snapshot', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_reviews', to='video_analysis.analysisjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'section'), name='va_identity_review_section')],
            },
        ),
        migrations.CreateModel(
            name='IdentityReviewAnswer',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(blank=True, db_default='', default='', max_length=16)),
                ('sequence', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='queued', max_length=16)),
                ('code', models.CharField(blank=True, max_length=24)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('revision', models.PositiveIntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_answers', to='video_analysis.analysisjob')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['job', 'section', 'status', 'sequence'], name='va_answer_order')],
            },
        ),
    ]
