# Generated by Django 6.1 on 2026-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='matchmvp',
            name='schedule_ma_match_i_2ed106_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchmvpvote',
            name='schedule_ma_match_i_5b6a08_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchmvpvote',
            name='schedule_ma_candida_77f876_idx',
        ),
    ]
