# Generated by Django 5.1.1 on 2024-10-11 08:43

import django.db.models.deletion
import uuidv7.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="/static/images/clubs/blank-club-picture.png",
                        upload_to="media/club_pictures/",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClubAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="club.club"
                    ),
                ),
            ],
        ),
    ]
