# Generated by Django 5.1.1 on 2024-10-11 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubadmin',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.player'),
        ),
        migrations.AddField(
            model_name='club',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='clubs', through='club.ClubAdmin', to='player.player'),
        ),
        migrations.AlterUniqueTogether(
            name='clubadmin',
            unique_together={('club', 'player')},
        ),
    ]
