# Generated by Django 5.1.4 on 2024-12-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_alter_club_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="club_pictures/"),
        ),
    ]
