# Generated by Django 6.1 on 2026-08-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_alter_club_logo'),
        ('player', '0021_remove_playerclubmembership_pcm_player_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubadmin',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='clubadmin',
            constraint=models.UniqueConstraint(fields=('club', 'player'), name='unique_club_admin'),
        ),
    ]
