# Generated by Django 6.1.1 on 2026-10-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_clubadmin_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='dissolved',
            field=models.BooleanField(db_default=False, default=False, help_text='The club no longer exists; it is kept for its historical matches.'),
        ),
    ]
