# Generated by Django 6.1.1 on 2026-10-03 08:37

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_club_dissolved'),
        ('player', '0034_player_account_setup'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubJoinRequest',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('member', 'Lid'), ('admin', 'Clubbeheerder')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'In behandeling'), ('approved', 'Geaccepteerd'), ('rejected', 'Afgewezen'), ('withdrawn', 'Ingetrokken')], db_default='pending', default='pending', max_length=16)),
                ('knkv_person_id', models.CharField(blank=True, max_length=80)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('link_status', models.CharField(blank=True, choices=[('', 'Geen'), ('pending', 'Wordt gekoppeld'), ('linked', 'Gekoppeld'), ('failed', 'Mislukt')], db_default='', default='', max_length=16)),
                ('link_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='club.club')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='player.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_join_requests', to='player.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='team.team')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['club', 'status'], name='club_join_club_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('player', 'club', 'kind'), name='unique_pending_club_join_request')],
            },
        ),
    ]
