# Generated by Django 5.2.7 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_initial'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['start_time'], name='schedule_ma_start_t_7cfb51_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['home_team'], name='schedule_ma_home_te_5e2ac9_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['away_team'], name='schedule_ma_away_te_6d06c4_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['season', 'start_time'], name='schedule_ma_season__13efe5_idx'),
        ),
    ]
