# Generated by Django 6.1 on 2026-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_legacy_mvp_state'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='schedule_ma_home_te_5e2ac9_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='schedule_ma_away_te_6d06c4_idx',
        ),
    ]
