# Generated by Django 6.1 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_remove_match_schedule_ma_home_te_5e2ac9_idx_and_more'),
        ('team', '0006_remove_teamdata_team_teamda_team_id_18931e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonpool',
            name='unique_pool_name_per_season',
        ),
        migrations.AddField(
            model_name='seasonpool',
            name='sport',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='seasonpool',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AddConstraint(
            model_name='seasonpool',
            constraint=models.UniqueConstraint(fields=('season', 'name', 'sport'), name='unique_pool_name_per_season_sport'),
        ),
    ]
