# Generated by Django 6.1.1 on 2026-09-08 20:07

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
        ('team', '0008_teamdata_staff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchNote',
            fields=[
                ('id', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=4000)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='schedule.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'indexes': [models.Index(fields=['match', 'team', '-created_at'], name='schedule_ma_match_i_f53e6a_idx')],
            },
        ),
    ]
