# Generated by Django 6.1.1 on 2026-09-09 09:24

from django.db import migrations, models


def validate_existing_rows(apps, schema_editor):
    """Fail before schema changes rather than silently rewriting sporting history."""
    matches = apps.get_model("schedule", "Match").objects.using(schema_editor.connection.alias)
    seasons = apps.get_model("schedule", "Season").objects.using(schema_editor.connection.alias)
    if matches.filter(home_team=models.F("away_team")).exists() or seasons.filter(end_date__lt=models.F("start_date")).exists():
        raise RuntimeError("Correct same-team fixtures and inverted season dates before applying schedule integrity constraints.")


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_matchnote'),
        ('team', '0009_remove_teamdata_team_teamda_team_id_f44f17_idx'),
    ]

    operations = [
        migrations.RunPython(validate_existing_rows, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='schedule_match_distinct_teams'),
        ),
        migrations.AddConstraint(
            model_name='season',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='season_valid_date_interval'),
        ),
    ]
