# Generated by Django 5.1.1 on 2024-10-11 08:43

import django.db.models.deletion
import bg_uuidv7.bg_uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("club", "0002_initial"),
        ("player", "0001_initial"),
        ("schedule", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=bg_uuidv7.bg_uuidv7.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="club.club",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competition", models.CharField(blank=True, max_length=255)),
                (
                    "coach",
                    models.ManyToManyField(
                        blank=True,
                        related_name="team_data_as_coach",
                        to="player.player",
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True,
                        related_name="team_data_as_player",
                        to="player.player",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_data",
                        to="schedule.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_data",
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
