# Generated by Django 5.1.1 on 2024-10-08 19:11

import django.db.models.deletion
import uuidv7.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('game_tracker', '0046_remove_club_admin_remove_team_club_and_more'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id_uuid', models.UUIDField(default=uuidv7.uuidv7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='TeamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.CharField(blank=True, max_length=255, null=True)),
                ('coach', models.ManyToManyField(blank=True, related_name='team_data_as_coach', to='game_tracker.player')),
                ('players', models.ManyToManyField(blank=True, related_name='team_data_as_player', to='game_tracker.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_data', to='schedule.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_data', to='team.team')),
            ],
        ),
    ]
