# Generated by Django 5.2.7 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_alter_player_user'),
        ('schedule', '0003_match_schedule_ma_start_t_7cfb51_idx_and_more'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='teamdata',
            index=models.Index(fields=['team'], name='team_teamda_team_id_18931e_idx'),
        ),
        migrations.AddIndex(
            model_name='teamdata',
            index=models.Index(fields=['season'], name='team_teamda_season__511bed_idx'),
        ),
        migrations.AddIndex(
            model_name='teamdata',
            index=models.Index(fields=['team', 'season'], name='team_teamda_team_id_f44f17_idx'),
        ),
    ]
