# Generated by Django 5.2.7 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_teamdata_team_teamda_team_id_18931e_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdata",
            name="wedstrijd_sport",
            field=models.BooleanField(default=False),
        ),
    ]
