# Generated by Django 5.2.7 on 2026-02-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_teamdata_wedstrijd_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="teamdata",
            name="team_rank",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
