# Generated by Django 6.1 on 2026-08-27 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teamdata',
            name='team_teamda_team_id_18931e_idx',
        ),
        migrations.RemoveIndex(
            model_name='teamdata',
            name='team_teamda_season__511bed_idx',
        ),
    ]
