# Generated by Django 6.1 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_clubadmin_unique_together_and_more'),
        ('player', '0021_remove_playerclubmembership_pcm_player_idx_and_more'),
        ('schedule', '0009_remove_seasonpool_unique_pool_name_per_season_and_more'),
        ('team', '0006_remove_teamdata_team_teamda_team_id_18931e_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('club', 'name'), name='unique_team_name_per_club'),
        ),
        migrations.AddConstraint(
            model_name='teamdata',
            constraint=models.UniqueConstraint(fields=('team', 'season'), name='unique_team_data_per_season'),
        ),
    ]
