# Generated by Django 6.1.1 on 2026-09-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0023_player_knkv_photo'),
        ('team', '0007_team_unique_team_name_per_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamdata',
            name='staff',
            field=models.ManyToManyField(blank=True, related_name='team_data_as_staff', to='player.player'),
        ),
    ]
