# Generated by Django 6.1.1 on 2026-09-09 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_teamdata_staff'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teamdata',
            name='team_teamda_team_id_f44f17_idx',
        ),
    ]
