# Generated by Django 6.1.1 on 2026-09-09 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_roster_history(apps, schema_editor):
    """Preserve current roles without inventing their historical start dates."""
    team_data = apps.get_model("team", "TeamData")
    history = apps.get_model("team", "TeamRosterMembership")
    alias = schema_editor.connection.alias
    for role in ("players", "coach", "staff"):
        through = getattr(team_data, role).through
        batch = []
        for data_id, player_id in through.objects.using(alias).values_list("teamdata_id", "player_id").iterator(chunk_size=1000):
            batch.append(history(team_data_id=data_id, player_id=player_id, role=role, started_at=None, source="legacy"))
            if len(batch) >= 1000:
                history.objects.using(alias).bulk_create(batch)
                batch.clear()
        history.objects.using(alias).bulk_create(batch)


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0025_player_archived_at'),
        ('team', '0009_remove_teamdata_team_teamda_team_id_f44f17_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRosterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('players', 'Player'), ('coach', 'Coach'), ('staff', 'Staff')], max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='native', max_length=32)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster_history', to='player.player')),
                ('team_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_history', to='team.teamdata')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('team_data', 'player', 'role'), name='unique_active_native_roster_role'), models.CheckConstraint(condition=models.Q(('started_at__isnull', True), ('ended_at__isnull', True), ('ended_at__gte', models.F('started_at')), _connector='OR'), name='native_roster_valid_interval')],
            },
        ),
        migrations.RunPython(backfill_roster_history, migrations.RunPython.noop),
    ]
