# Generated by Django 6.1.1 on 2026-09-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("player", "0026_playergoalsongselection_teamgoalsongselection"),
        ('team', '0010_teamrostermembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamdata',
            name='fallback_goal_song_song_ids',
        ),
    ]
