# Generated by Django 5.1.1 on 2026-02-15 00:00

import bg_uuidv7.bg_uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=bg_uuidv7.bg_uuidv7.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("source_system", models.CharField(db_index=True, max_length=64)),
                ("event_name", models.CharField(db_index=True, max_length=128)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("actor_type", models.CharField(blank=True, default="", max_length=64)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                (
                    "subject_type",
                    models.CharField(blank=True, db_index=True, default="", max_length=64),
                ),
                (
                    "subject_id",
                    models.CharField(blank=True, db_index=True, default="", max_length=128),
                ),
                ("club_id", models.CharField(blank=True, db_index=True, default="", max_length=64)),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(default=dict)),
                ("payload", models.JSONField(default=dict)),
                (
                    "ingested_via",
                    models.CharField(db_index=True, default="api", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-occurred_at", "source_system"],
                        name="audit_timeline_idx",
                    ),
                    models.Index(
                        fields=["event_name", "actor_id", "club_id"],
                        name="audit_lookup_idx",
                    ),
                ],
            },
        ),
    ]
