# Generated by Django 5.1.1 on 2024-10-11 08:43

import uuidv7.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GoalType",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroupTypes",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="MatchData",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("home_score", models.IntegerField(default=0)),
                ("away_score", models.IntegerField(default=0)),
                ("parts", models.IntegerField(default=2)),
                ("current_part", models.IntegerField(default=1)),
                ("part_lenght", models.IntegerField(default=1800)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatchPart",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("part_number", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pause",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerChange",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerGroup",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Shot",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("for_team", models.BooleanField(default=True)),
                ("scored", models.BooleanField(default=False)),
                ("time", models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
    ]
