# Generated by Django 5.1.1 on 2024-10-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchpart",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
