# Generated by Django 5.1.1 on 2024-10-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0003_matchpart_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="pause",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
