# Generated by Django 5.1.3 on 2024-12-04 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0006_grouptypes_order"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupTypes",
            new_name="GroupType",
        ),
    ]
