# Generated by Django 5.1.4 on 2025-01-29 15:54

import django.db.models.deletion
import uuidv7.uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0008_rename_part_lenght_matchdata_part_length"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeout",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=uuidv7.uuidv7.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "match_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeouts",
                        to="game_tracker.matchdata",
                    ),
                ),
                (
                    "match_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_tracker.matchpart",
                    ),
                ),
                (
                    "pause",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_tracker.pause",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
