# Generated by Django 5.1.4 on 2025-01-29 16:34

import django.db.models.deletion
import bg_uuidv7.bg_uuidv7
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0009_timeout"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attack",
            fields=[
                (
                    "id_uuid",
                    models.UUIDField(
                        default=bg_uuidv7.bg_uuidv7.uuidv7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "match_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks",
                        to="game_tracker.matchdata",
                    ),
                ),
                (
                    "match_part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game_tracker.matchpart",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="team.team",
                    ),
                ),
            ],
        ),
    ]
