# Generated by Django 5.2.7 on 2025-10-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0010_attack'),
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='matchdata',
            index=models.Index(fields=['status'], name='game_tracke_status_8c8f6e_idx'),
        ),
        migrations.AddIndex(
            model_name='matchdata',
            index=models.Index(fields=['match_link'], name='game_tracke_match_l_91ae7b_idx'),
        ),
        migrations.AddIndex(
            model_name='matchdata',
            index=models.Index(fields=['status', 'match_link'], name='game_tracke_status_b7f118_idx'),
        ),
    ]
