# Generated by Django 5.2.7 on 2025-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0011_matchdata_game_tracke_status_8c8f6e_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playerchange",
            name="player_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                related_name="player_changes",
                to="player.player",
            ),
        ),
        migrations.AlterField(
            model_name="playerchange",
            name="player_out",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                to="player.player",
            ),
        ),
    ]
