# Generated by Django 5.2.15 on 2026-08-23 11:25

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0022_matchlivechange'),
        ('team', '0005_teamdata_fallback_goal_song_song_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerCommand',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('command_id', models.UUIDField()),
                ('sequence', models.PositiveBigIntegerField()),
                ('command', models.CharField(max_length=40)),
                ('payload_hash', models.CharField(max_length=64)),
                ('expected_revision', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchdata',
            name='command_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trackercommand',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracker_commands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackercommand',
            name='match_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_commands', to='game_tracker.matchdata'),
        ),
        migrations.AddField(
            model_name='trackercommand',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tracker_commands', to='team.team'),
        ),
        migrations.AddIndex(
            model_name='trackercommand',
            index=models.Index(fields=['match_data', '-sequence'], name='tracker_cmd_match_seq_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackercommand',
            constraint=models.UniqueConstraint(fields=('match_data', 'command_id'), name='game_tracker_unique_command_id'),
        ),
        migrations.AddConstraint(
            model_name='trackercommand',
            constraint=models.UniqueConstraint(fields=('match_data', 'sequence'), name='game_tracker_unique_command_sequence'),
        ),
    ]
