# Generated by Django 5.2.15 on 2026-08-23 11:32

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_match_events(apps, schema_editor):
    """Assign a deterministic envelope sequence to existing typed records."""
    del schema_editor
    MatchData = apps.get_model("game_tracker", "MatchData")
    MatchEvent = apps.get_model("game_tracker", "MatchEvent")
    sources = (
        ("attack", apps.get_model("game_tracker", "Attack"), "time"),
        ("match_part", apps.get_model("game_tracker", "MatchPart"), "start_time"),
        ("pause", apps.get_model("game_tracker", "Pause"), "start_time"),
        (
            "player_change",
            apps.get_model("game_tracker", "PlayerChange"),
            "time",
        ),
        ("shot", apps.get_model("game_tracker", "Shot"), "time"),
    )
    Timeout = apps.get_model("game_tracker", "Timeout")

    for match_data in MatchData.objects.all().iterator():
        rows = []
        for source_type, model, time_field in sources:
            for source_id, effective_at in model.objects.filter(
                match_data_id=match_data.pk
            ).values_list("pk", time_field):
                rows.append((effective_at, source_type, source_id))
        for source_id, effective_at in Timeout.objects.filter(
            match_data_id=match_data.pk
        ).values_list("pk", "pause__start_time"):
            rows.append((effective_at, "timeout", source_id))

        rows.sort(
            key=lambda row: (
                row[0] is None,
                row[0] or match_data.live_changed_at,
                row[1],
                str(row[2]),
            )
        )
        MatchEvent.objects.bulk_create(
            [
                MatchEvent(
                    match_data_id=match_data.pk,
                    sequence=sequence,
                    kind=(
                        f"{source_type}.started"
                        if source_type in {"match_part", "pause"}
                        else f"{source_type}.created"
                    ),
                    source_type=source_type,
                    source_id=source_id,
                    effective_at=effective_at,
                    payload={"operation": "created", "backfilled": True},
                )
                for sequence, (effective_at, source_type, source_id) in enumerate(
                    rows, start=1
                )
            ]
        )
        MatchData.objects.filter(pk=match_data.pk).update(event_sequence=len(rows))


def reverse_backfill_match_events(apps, schema_editor):
    """Remove backfilled envelopes before reversing the schema migration."""
    del schema_editor
    apps.get_model("game_tracker", "MatchEvent").objects.all().delete()
    apps.get_model("game_tracker", "MatchData").objects.update(event_sequence=0)


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0023_trackercommand_and_more'),
        ('team', '0005_teamdata_fallback_goal_song_song_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveBigIntegerField()),
                ('kind', models.CharField(max_length=64)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.UUIDField()),
                ('effective_at', models.DateTimeField(blank=True, null=True)),
                ('elapsed_ms', models.PositiveBigIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('command_id', models.UUIDField(blank=True, null=True)),
                ('payload_version', models.PositiveSmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('superseded', 'Superseded'), ('retracted', 'Retracted')], default='active', max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='matchdata',
            name='event_sequence',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_match_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='match_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_events', to='game_tracker.matchdata'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='source_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_match_events', to='team.team'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='game_tracker.matchevent'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match_data', '-sequence'], name='match_event_match_seq_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match_data', 'source_type', 'source_id', 'status'], name='match_event_source_idx'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match_data', 'effective_at'], name='match_event_effective_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchevent',
            constraint=models.UniqueConstraint(fields=('match_data', 'sequence'), name='game_tracker_unique_event_sequence'),
        ),
        migrations.RunPython(
            backfill_match_events,
            reverse_code=reverse_backfill_match_events,
        ),
    ]
