# Generated by Django 5.2.15 on 2026-08-23 11:47

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.db import migrations, models


def backfill_starting_assignments(apps, schema_editor):
    """Deduplicate rosters and reconstruct historical starting lineups."""
    del schema_editor
    MatchData = apps.get_model("game_tracker", "MatchData")
    MatchPlayer = apps.get_model("game_tracker", "MatchPlayer")
    PlayerChange = apps.get_model("game_tracker", "PlayerChange")
    PlayerGroup = apps.get_model("game_tracker", "PlayerGroup")
    StartingAssignment = apps.get_model(
        "game_tracker", "StartingPlayerAssignment"
    )

    seen_roster_players = set()
    duplicate_roster_ids = []
    for row_id, match_data_id, player_id in MatchPlayer.objects.order_by(
        "id_uuid"
    ).values_list("id_uuid", "match_data_id", "player_id"):
        key = (match_data_id, player_id)
        if key in seen_roster_players:
            duplicate_roster_ids.append(row_id)
        else:
            seen_roster_players.add(key)
    MatchPlayer.objects.filter(id_uuid__in=duplicate_roster_ids).delete()

    through = PlayerGroup.players.through
    for match_data in MatchData.objects.exclude(status="upcoming").iterator():
        groups = list(
            PlayerGroup.objects.filter(match_data_id=match_data.pk).values(
                "id_uuid", "team_id", "starting_type__name"
            )
        )
        group_ids = {group["id_uuid"] for group in groups}
        players_by_group = {
            group_id: set(
                through.objects.filter(playergroup_id=group_id).values_list(
                    "player_id", flat=True
                )
            )
            for group_id in group_ids
        }
        reserve_by_team = {
            group["team_id"]: group["id_uuid"]
            for group in groups
            if group["starting_type__name"] == "Reserve"
        }
        team_by_group = {
            group["id_uuid"]: group["team_id"] for group in groups
        }
        changes = list(
            PlayerChange.objects.filter(match_data_id=match_data.pk).values(
                "id_uuid",
                "time",
                "player_in_id",
                "player_out_id",
                "player_group_id",
            )
        )
        changes.sort(
            key=lambda change: (
                change["time"] is None,
                change["time"] or match_data.live_changed_at,
                str(change["id_uuid"]),
            ),
            reverse=True,
        )
        for change in changes:
            player_in_id = change["player_in_id"]
            player_out_id = change["player_out_id"]
            target_group_id = change["player_group_id"]
            if (
                player_in_id is None
                or player_out_id is None
                or target_group_id not in group_ids
            ):
                continue
            team_id = team_by_group[target_group_id]
            team_group_ids = {
                group_id
                for group_id, candidate_team_id in team_by_group.items()
                if candidate_team_id == team_id
            }
            for group_id in team_group_ids:
                players_by_group[group_id].discard(player_in_id)
                players_by_group[group_id].discard(player_out_id)
            reserve_group_id = reserve_by_team.get(team_id)
            if reserve_group_id is not None:
                players_by_group[reserve_group_id].add(player_in_id)
            players_by_group[target_group_id].add(player_out_id)

        assignments_by_player = {}
        ordered_groups = sorted(
            groups,
            key=lambda group: group["starting_type__name"] == "Reserve",
        )
        for group in ordered_groups:
            group_id = group["id_uuid"]
            for player_id in players_by_group[group_id]:
                assignments_by_player.setdefault(player_id, group_id)
        StartingAssignment.objects.bulk_create(
            [
                StartingAssignment(
                    match_data_id=match_data.pk,
                    player_group_id=group_id,
                    player_id=player_id,
                )
                for player_id, group_id in assignments_by_player.items()
            ]
        )


def reverse_starting_assignments(apps, schema_editor):
    """Remove generated starting-lineup snapshots."""
    del schema_editor
    apps.get_model(
        "game_tracker", "StartingPlayerAssignment"
    ).objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0024_matchevent_and_more'),
        ('player', '0020_enqueue_goal_song_clip_preparation'),
        ('team', '0005_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartingPlayerAssignment',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='startingplayerassignment',
            name='match_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_player_assignments', to='game_tracker.matchdata'),
        ),
        migrations.AddField(
            model_name='startingplayerassignment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_match_assignments', to='player.player'),
        ),
        migrations.AddField(
            model_name='startingplayerassignment',
            name='player_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_player_assignments', to='game_tracker.playergroup'),
        ),
        migrations.RunPython(
            backfill_starting_assignments,
            reverse_code=reverse_starting_assignments,
        ),
        migrations.AddConstraint(
            model_name='matchplayer',
            constraint=models.UniqueConstraint(fields=('match_data', 'player'), name='game_tracker_unique_match_player'),
        ),
        migrations.AddIndex(
            model_name='startingplayerassignment',
            index=models.Index(fields=['match_data', 'player_group'], name='starting_assignment_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='startingplayerassignment',
            constraint=models.UniqueConstraint(fields=('match_data', 'player'), name='game_tracker_unique_starting_player'),
        ),
    ]
