# Generated by Django 6.1 on 2026-08-27 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0031_align_decimal_field_defaults'),
        ('schedule', '0008_remove_match_schedule_ma_home_te_5e2ac9_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='matchdata',
            name='uniq_match_data_per_match',
        ),
        migrations.RemoveIndex(
            model_name='matchdata',
            name='game_tracke_match_l_91ae7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchlivechange',
            name='game_tracke_match_d_23208e_idx',
        ),
        migrations.RemoveIndex(
            model_name='matchplayer',
            name='mp_match_player_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchimpact',
            name='impact_match_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchimpact',
            name='impact_team_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchimpact',
            name='impact_player_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchminutes',
            name='minutes_match_idx',
        ),
        migrations.RemoveIndex(
            model_name='playermatchminutes',
            name='minutes_player_idx',
        ),
        migrations.AlterField(
            model_name='matchdata',
            name='match_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_data', to='schedule.match'),
        ),
    ]
