# Generated by Django 6.1 on 2026-08-28 17:47

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0033_player_match_impact_precision'),
        ('player', '0021_remove_playerclubmembership_pcm_player_idx_and_more'),
        ('team', '0006_remove_teamdata_team_teamda_team_id_18931e_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossessionChangeEventDetail',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='possession_change_detail', serialize=False, to='game_tracker.matchevent')),
                ('kind', models.CharField(max_length=16)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_possession_change_events', to='player.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_possession_change_events', to='team.team')),
            ],
        ),
        migrations.CreateModel(
            name='PossessionChange',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ball_loss', 'Ball loss'), ('interception', 'Interception')], max_length=16)),
                ('time', models.DateTimeField()),
                ('match_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_changes', to='game_tracker.matchdata')),
                ('match_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_changes', to='game_tracker.matchpart')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='possession_changes', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possession_changes', to='team.team')),
            ],
            options={
                'indexes': [models.Index(fields=['match_data', 'time'], name='poss_change_match_time_idx'), models.Index(fields=['match_data', 'player', 'kind'], name='poss_change_player_kind_idx')],
            },
        ),
    ]
