# Generated by Django 6.1 on 2026-08-29 11:29

from decimal import Decimal
from django.db import migrations, models


def delete_stale_v8_impacts(apps, _schema_editor):
    """Force derived v8 rows to be rebuilt with WPA after deployment."""
    player_match_impact = apps.get_model("game_tracker", "PlayerMatchImpact")
    player_match_impact.objects.filter(algorithm_version="v8").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game_tracker", "0034_possessionchangeeventdetail_possessionchange"),
    ]

    operations = [
        migrations.AddField(
            model_name='playermatchimpact',
            name="win_probability_added",
            field=models.DecimalField(
                decimal_places=5,
                default=Decimal("0.00000"),
                max_digits=9,
            ),
        ),
        migrations.RunPython(delete_stale_v8_impacts, migrations.RunPython.noop),
    ]
