# Generated by Django 6.1 on 2026-09-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0035_player_match_impact_wpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='score_source',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('knkv', 'KNKV')], default='tracker', max_length=16),
        ),
    ]
