# Generated by Django 6.1 on 2026-09-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0036_matchdata_score_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='score_source',
            field=models.CharField(choices=[('tracker', 'Tracker'), ('knkv', 'KNKV'), ('archive', 'Archive')], default='tracker', max_length=16),
        ),
    ]
