# Generated by Django 6.1.1 on 2026-09-09 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0037_alter_matchdata_score_source'),
        ('schedule', '0010_matchnote'),
        ('team', '0008_teamdata_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerAccessLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('match', 'team'), name='unique_tracker_access_match_team')],
            },
        ),
    ]
