# Generated by Django 6.1.1 on 2026-09-09 09:24

import django.db.models.deletion
from django.db import migrations, models


def validate_existing_rows(apps, schema_editor):
    """Fail before schema changes rather than silently rewriting sporting history."""
    matches = apps.get_model("game_tracker", "MatchData").objects.using(schema_editor.connection.alias)
    if matches.filter(models.Q(home_score__lt=0) | models.Q(away_score__lt=0) | models.Q(parts__lt=1) | models.Q(current_part__lt=1) | models.Q(part_length__lt=1)).exists():
        raise RuntimeError("Correct negative scores and nonpositive period settings before applying tracker integrity constraints.")


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0037_alter_matchdata_score_source'),
        ('player', '0024_alter_player_user'),
        ('schedule', '0011_match_schedule_match_distinct_teams_and_more'),
        ('team', '0009_remove_teamdata_team_teamda_team_id_f44f17_idx'),
    ]

    operations = [
        migrations.RunPython(validate_existing_rows, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='playermatchimpact',
            name='uniq_player_match_impact',
        ),
        migrations.AddField(
            model_name='playermatchimpact',
            name='source_revision',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='playermatchminutes',
            name='source_revision',
            field=models.PositiveBigIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_players', to='player.player'),
        ),
        migrations.AlterField(
            model_name='playerchange',
            name='player_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='player_changes', to='player.player'),
        ),
        migrations.AlterField(
            model_name='playerchange',
            name='player_out',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='player.player'),
        ),
        migrations.AlterField(
            model_name='playermatchimpact',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_impacts', to='player.player'),
        ),
        migrations.AlterField(
            model_name='playermatchminutes',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_minutes', to='player.player'),
        ),
        migrations.AlterField(
            model_name='shot',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shots', to='player.player'),
        ),
        migrations.AlterField(
            model_name='startingplayerassignment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='starting_match_assignments', to='player.player'),
        ),
        migrations.AddConstraint(
            model_name='matchdata',
            constraint=models.CheckConstraint(condition=models.Q(('away_score__gte', 0), ('home_score__gte', 0)), name='match_data_nonnegative_scores'),
        ),
        migrations.AddConstraint(
            model_name='matchdata',
            constraint=models.CheckConstraint(condition=models.Q(('current_part__gte', 1), ('part_length__gte', 1), ('parts__gte', 1)), name='match_data_positive_periods'),
        ),
        migrations.AddConstraint(
            model_name='playermatchimpact',
            constraint=models.UniqueConstraint(fields=('match_data', 'player', 'algorithm_version'), name='uniq_player_match_impact'),
        ),
    ]
