# Generated by Django 6.1.1 on 2026-09-09 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0038_remove_playermatchimpact_uniq_player_match_impact_and_more'),
        ('game_tracker', '0038_tracker_access_link'),
    ]

    operations = [
    ]
