# Generated by Django 6.1.1 on 2026-09-10 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("game_tracker", "0039_merge_20260909_1525"),
        ("game_tracker", "0039_merge_access_and_integrity"),
    ]

    operations = []
