# Generated by Django 6.1.1 on 2026-09-12 06:54

from django.db import migrations, models


def restore_recorded_captains(apps, schema_editor):
    """Keep the latest confirmed imported/published captain when still selected."""
    database = schema_editor.connection.alias
    jobs = apps.get_model("competition", "MatchFormSync")
    match_players = apps.get_model("game_tracker", "MatchPlayer")
    seen = set()
    for job in (
        jobs.objects.using(database)
        .filter(action__in=["import", "publish"], state="succeeded")
        .select_related("access")
        .order_by("-updated_at", "-pk")
        .iterator()
    ):
        scope = (job.match_id, job.access.team_id)
        if scope in seen:
            continue
        seen.add(scope)
        match_players.objects.using(database).filter(
            match_data__match_link_id=job.match_id,
            team_id=job.access.team_id,
            player_id=job.captain_player_id,
            player__archived_at__isnull=True,
            player__player_groups__match_data__match_link_id=job.match_id,
            player__player_groups__team_id=job.access.team_id,
        ).exclude(player__knkv_privacy="PRIVATE").update(is_captain=True)


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0023_matchformsync_captain_player"),
        ("game_tracker", "0040_merge_duplicate_heads"),
        ("player", "0028_alter_player_profile_picture_and_more"),
        ("team", "0011_remove_teamdata_fallback_goal_song_song_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchplayer",
            name="is_captain",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(restore_recorded_captains, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="matchplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_captain", True)),
                fields=("match_data", "team"),
                name="game_tracker_unique_team_captain",
            ),
        ),
    ]
