# Generated by Django 6.1.1 on 2026-09-25 21:28

import bg_uuidv7.bg_uuidv7
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0041_matchplayer_captain'),
        ('player', '0031_playersong_library_source_and_more'),
        ('team', '0011_remove_teamdata_fallback_goal_song_song_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchGuestPlayer',
            fields=[
                ('id_uuid', models.UUIDField(default=bg_uuidv7.bg_uuidv7.uuidv7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_players', to='game_tracker.matchdata')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest', to='player.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_guest_players', to='team.team')),
            ],
            options={
                'indexes': [models.Index(fields=['match_data', 'team'], name='mgp_match_team_idx')],
            },
        ),
    ]
