# Generated by Django 6.1.1 on 2026-10-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_tracker', '0042_matchguestplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='rules',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='rules_pending',
            field=models.JSONField(blank=True, db_default=models.Value({}, output_field=models.JSONField()), default=dict),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='rules_source',
            field=models.CharField(choices=[('official_timing', 'official_timing'), ('edition_rules', 'edition_rules'), ('manual', 'manual'), ('assumed_default', 'assumed_default')], db_default='assumed_default', default='assumed_default', max_length=20),
        ),
    ]
