name: Linters

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read

jobs:
    flake8:
        if: ${{ !contains(github.event.head_commit.message, 'Sync from monorepo') }}
        name: flake8
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Cache pip
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-flake8
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - run: python -m pip install flake8

            - name: flake8
              uses: liskin/gh-problem-matcher-wrap@e7b7beaaafa52524748b31a381160759d68d61fb
              with:
                  linters: flake8
                  run: flake8 --exclude=migrations

    isort:
        if: ${{ !contains(github.event.head_commit.message, 'Sync from monorepo') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Cache pip
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-isort
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - run: python -m pip install isort

            - name: isort
              uses: liskin/gh-problem-matcher-wrap@e7b7beaaafa52524748b31a381160759d68d61fb
              with:
                  linters: isort
                  run: isort --check --diff . --skip=migrations

    black:
        if: ${{ !contains(github.event.head_commit.message, 'Sync from monorepo') }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.13'

            - name: Cache pip
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-black
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - run: python -m pip install black

            - name: Black
              run: black --check --diff .
